### ISSUE TITLE
fails to load

### ISSUE THREAD

**Issue by robertfgoodworth** [simonhq/canberradams#1]
Hi There,
Please help, via HASSIO i've installed appdaemon4, then proceeded to install canberradams via the community repo. all looks to install correctly, upon starting appdaemon4 i get the following in the log.

2020-04-01 09:42:55.214389 WARNING Error: ------------------------------------------------------------
2020-04-01 09:42:55.214789 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/canberradams/canberradams.py:
2020-04-01 09:42:55.215161 WARNING Error: ------------------------------------------------------------
2020-04-01 09:42:55.216584 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 788, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 580, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/canberradams/canberradams.py", line 31, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

2020-04-01 09:42:55.216777 WARNING Error: ------------------------------------------------------------
2020-04-01 09:42:55.216968 WARNING AppDaemon: Removing associated apps:
2020-04-01 09:42:55.217161 WARNING AppDaemon: canberra_dams
2020-04-01 09:42:55.217617 INFO AppDaemon: App initialization complete

I checked python, bs4 and BeautifulSoup are installed. my HA (HASSIO) is running on Ubuntu 18.04 with python 3.8.0-3~18.04

Please help a local canberrian stuck at home,

**Comment by simonhq** [comment]
Hi robertfgoodworth,

Can you check that you have the bs4 folder in your appdaemon directory please, mine looks like this;

![image](https://user-images.githubusercontent.com/18653928/78083472-53ec3600-7401-11ea-8952-479b445b470e.png)

I did this ages ago, but am pretty sure after I installed bs4 through pip, I just copied the whole bs4 folder from where it 'installed' it to the apps folder in appdaemon.

Let me know if you need a hand, but I think if you use the find or locate command to find the bs4 folder and then the cp -R command to copy it into the directory you should be right.

Simon

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Well I’ll be, that did the trick.  THANKYOU

 

Should it show each dam level?  The sensor only give me a single figure 50.57. 

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

H: 02 62939660

M: 0428699792

robertfgoodworth@bigpond.com <mailto:robertfgoodworth@bigpond.com>   NOTE:  NEW EMAIL

**Comment by simonhq** [comment]
Hi Robert,

Great! glad it is working for you, currently yes I have it only providing the overall volume, because I am scraping the website, only some of the values are easy to get, other websites have the split but they don't update as often or worse the BOM and Icon water disagree on what Dams belong to the ACT water supply so have different values!

Btw I am over in Isabella Plains, so when we are released from lock down we should catch up for a chat sometime.

Simon.

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Thanks, I’m over at Bonython, happy for you to use my private email address below. When the lockdown is over I’d like to catchup.

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

robertfgoodworth@bigpond.com <mailto:robertfgoodworth@bigpond.com>

**Comment by simonhq** [comment]
Hi Robert,

Just a quick message that i have updated the dams app to make it a bit more useful.

You no longer need bs4 (beautiful soup), but you do need a different library (xmltodict)
I worked out how to have libraries (like bs4/xmltodict) available at the appdaemon level - info in the readme
I have removed the need to provide the name of the sensor
It now creates 5 sensors, one for each dam, a combined dam level and the last time it updated

let me know of any issues, hope you are staying well and sane

Simon.

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Thanks for the update, I’ll be sure to check it out.

 

I’m not sure how to do the following, I’m not a Appdaemon user. Do I just add this to my appdaemon.yaml file ?

 

Please add the following packages to your appdaemon configuration

system_packages: []

python_packages:

  - xmltodict

init_commands: []

 

 

 

We are well and sane, hope you are too.

 

Regards

 

Robert

**Comment by simonhq** [comment]
Are you using the appdaemon add-in for hassio?

When I go into the add-in screen (where you restart appdaemon), there is a configuration area, that has the three areas for packages that will be installed on each start of appdaemon.

I also install - bs4 in the python packages now for some of my other code so that I don't need to have it like I described to you earlier.

Simon.

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

I didn’t have much luck.  I get the following error in the appdaemon log.

 

2020-05-04 20:22:14.585101 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/canberradams/canberradams.py

2020-05-04 20:22:14.590104 WARNING Error: ------------------------------------------------------------

2020-05-04 20:22:14.590373 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/canberradams/canberradams.py:

2020-05-04 20:22:14.590604 WARNING Error: ------------------------------------------------------------

2020-05-04 20:22:14.591842 WARNING Error: Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 788, in check_app_updates

    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])

  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor

    response = future.result()

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 580, in read_app

    self.modules[module_name] = importlib.import_module(module_name)

  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 991, in _find_and_load

  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 783, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/config/appdaemon/apps/canberradams/canberradams.py", line 33, in <module>

    import globals

ModuleNotFoundError: No module named 'globals'

 

 

Any hints ??

 

 

Regards

 

Robert Goodworth

**Comment by simonhq** [comment]
Hi Robert,

It looks like you don't have the globals.py file in you /appdaemon/apps directory, which I actually thought was standard. I am confused as the last version used this as well. Can you check in you apps directory and in apps.yaml to make sure that globals is correct? if not I will see if I can get my version of globals to you.

Simon.

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Sorry for bothering you again.

 

Got me a little closer “I think” 😊. I found that “globals.py” file in the “/custom_components/HACS/” directory, so I copied over to “/appsdaemon/apps/” directory as you mentioned.

 

Getting this now:

 

2020-05-05 18:09:27.660453 INFO AppDaemon: Initializing app canberra_dams using class Get_ACT_Dams from module canberradams

2020-05-05 18:09:27.698154 INFO events: Monitoring {'event':'call_service', 'data':{'domain': 'switch'}}

2020-05-05 18:09:27.699534 WARNING AppDaemon: Unable to find module deconz_helper - initialize() skipped

2020-05-05 18:09:27.700515 WARNING canberra_dams: ------------------------------------------------------------

2020-05-05 18:09:27.700800 WARNING canberra_dams: Unexpected error running initialize() for canberra_dams

2020-05-05 18:09:27.701036 WARNING canberra_dams: ------------------------------------------------------------

2020-05-05 18:09:27.702001 WARNING canberra_dams: Traceback (most recent call last):

  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app

    await utils.run_in_executor(self, init)

  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor

    response = future.result()

  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/config/appdaemon/apps/canberradams/canberradams.py", line 51, in initialize

    self.DAM_FLAG = globals.get_arg(self.args, "DAM_FLAG")

AttributeError: module 'globals' has no attribute 'get_arg'

 

2020-05-05 18:09:27.702198 WARNING canberra_dams: ------------------------------------------------------------

2020-05-05 18:09:27.702768 INFO AppDaemon: App initialization complete

 

Any idea’s ?

 

 

Regards

 

Robert Goodworth

**Comment by simonhq** [comment]
Hi Robert,

Are you using AppDaemon 3 or 4?

It seems strange that your globals.py file isn't the same as mine. Though I can't remember whether it is a standard thing or if I got it from somewhere different. 

Simon.

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Yep it’s Appdaemon 4, below is the globals.py, looks very HACS oriented.

 

 

# pylint: disable=invalid-name, missing-docstring

hacs = []

removed_repositories = []

 

def get_hacs():

    if not hacs:

        from custom_components.hacs.hacsbase import Hacs

 

        hacs.append(Hacs())

 

    return hacs[0]

 

def is_removed(repository):

    return repository in [x.repository for x in removed_repositories]

 

def get_removed(repository):

    if not is_removed(repository):

        from custom_components.hacs.repositories.removed import RemovedRepository

 

        removed_repo = RemovedRepository()

        removed_repo.repository = repository

        removed_repositories.append(removed_repo)

    filter_repos = [

        x for x in removed_repositories if x.repository.lower() == repository.lower()

    ]

    return filter_repos[0]

 

 

_______________________________________________________

 

 

Regards

 

Robert Goodworth

**Comment by simonhq** [comment]
Hey Robert,

Just implemented a change to remove the need for globals.py, hopefully it should work now. 

Let me know of any other problems,

Simon

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Gotta love this Github update process in HA,  It worked a charm, yeeha.

 

Question, is your app able to scrap say the Snowy Hydro site for there Dam levels as well?

We often go to Buckenderra with our Caravan, keeping an eye on the eucumbene dam level would be cool.

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

H: 02 62939660

M: 0428699792

robertfgoodworth@bigpond.com <mailto:robertfgoodworth@bigpond.com>   NOTE:  NEW EMAIL

**Comment by simonhq** [comment]
Hi Robert,

I have had a look and it appears that I can get the three snowy dams information, I will have a look on the weekend and see if I can set something up. If I get something working I will send you a link to test it.

Simon

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Happy to test 😊

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

H: 02 62939660

M: 0428699792

robertfgoodworth@bigpond.com <mailto:robertfgoodworth@bigpond.com>   NOTE:  NEW EMAIL

**Comment by simonhq** [comment]
Hi Robert,
Morning, I have put together another couple of apps that you may be interested in.
They are here:
https://github.com/simonhq/snowydams 
https://github.com/simonhq/accu_allergies
You can add them manually into HACS for testing on the HACS settings page just by entering the paths and changing the type to AppDaemon App, then they will show up on the AppDaemon Apps page to let you install them.  

You will still need to follow the instructions to set them up once they are installed.
Let me know if you have any problems.
Simon

btw the icon water web page is down at the moment - so the canberra dams one is not working...

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

WOW that was fast, I’ve added it, only feedback is the app configuration in the readme shows  the following,

 

canberra_dams:

  module: snowydams

  class: Get_Snowy_Dams

  DAM_FLAG: "input_boolean.check_snowy_dams"

 

 

It should show 

 

snowy_dams:

#   module: snowydams

#   class: Get_Snowy_Dams

#   DAM_FLAG: "input_boolean.check_snowy_dams"

Yeah?

 

 

Regards

 

Robert Goodworth

**Comment by simonhq** [comment]
Thanks Robert,

I have fixed that, I will leave it for a few days to make sure we don't get any errors, then I will make it a HACS default, then it will just be a standard like the other dams one. It should then disappear from your manual settings.

Simon.

**Comment by robertfgoodworth** [comment]
Thanks Simon,

 

Great job by the way, I appreciate your efforts.

 

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

H: 02 62939660

M: 0428699792

robertfgoodworth@bigpond.com <mailto:robertfgoodworth@bigpond.com>   NOTE:  NEW EMAIL

**Comment by simonhq** [comment]
Hi Robert,

Another one to test if you are interested

https://github.com/simonhq/act_garbage

Did you look at the allergies one? no problems if you didn't just wondering.

Simon.

**Comment by robertfgoodworth** [comment]
Hi Simon,

 

Looks good, you’re a wizz at this.

 

I see the following sensors

 



 

I change suburb to “BONYTHON”

 

 

 

Regards

 

Robert Goodworth

21 Harcus Close 

Bonython, ACT, 2905

H: 02 62939660

M: 0428699792

robertfgoodworth@bigpond.com <mailto:robertfgoodworth@bigpond.com>   NOTE:  NEW EMAIL
